### ISSUE TITLE
numpy operation

### ISSUE THREAD

**Issue by vick2075** [python/psf-infra-meta#100]
I stumbled onto something very peculiar and am wondering if it is a Python bug or it's something I did not properly understand with regard to Numpy arrays.

I'm computing the Kernel trick:

(c + np.matmul(x1, x2.T)) ** n
n = nth power; c = free parameter

Let x1 be (3,6) and x2 = (10, 10)

Computing the matmul should result in 90. However when I use c=2 and n=5; the result is incorrect! It gives -1999119360 instead of 6590815232!

Am I doing something wrong with the code? Or is it a bug? Because when you decrease n, the results are correct!

**Comment by matrixise** [comment]
@pablogsal I don't have the access to this tracker, but this issue is unrelated to the PSF infra. Do you think you could close this one? Thanks

**Comment by pablogsal** [comment]
I don't have access either

**Comment by pradyunsg** [comment]
@ewdurbin should be able to close this.
