### ISSUE TITLE
for string methods strip, lstrip, rstrip, when param is a string which has more than one char, those methods is no useful currently

### ISSUE THREAD

**Issue by redrose2100** [python/psf-infra-meta#114]
for string methods strip, lstrip, rstrip, when param is a string which has more than 1 char, currently those methods remove char ,but not remove string , it is no useful 

following is the results in python 3.9.5

```python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> s="hellolloehb"
>>> print(s.lstrip("hello"))
b
>>> s="blloehhello"
>>> print(s.rstrip("hello"))
b
>>> s="helloehhollbllohhehello"
>>> print(s.strip("hello"))
b
>>>
```

In fact,
when s="hellolloehb" , s.lstrip("hello") expect to get "lloehb"
when s="blloehhello" , s.rstrip("hello") expect to get "blloeh"
when s="helloehhollbllohhehello" , s.strip("hello") expect to get "ehhollbllohhe"

**Comment by matrixise** [comment]
Unrelated to this project, please open an issue in the official bug tracker of Python or ask on a user mailing list.
