### ISSUE TITLE
https://hg.python.org/ is down

### ISSUE THREAD

**Issue by vstinner** [python/psf-infra-meta#115]
https://hg.python.org/ currently says:

```
503 Service Unavailable
No server is available to handle this request. 
```

I was looking for https://hg.python.org/cpython/rev/3c43be281196 link from https://bugs.python.org/issue14424#msg162191

**Comment by graingert** [comment]
@vstinner seems to be working now

**Comment by vstinner** [comment]
> @vstinner seems to be working now

Right. Magic happens! I close my issue.
