### ISSUE TITLE
** opeator issue on negative number with even exponent

### ISSUE THREAD

**Issue by Xenox-Inno** [python/psf-infra-meta#132]
Hi, I'm using python 3.9.9. When i using pow operator ** on negative integer with even exponent such as 2, the return value is also negative. However when i using math.pow, the return value will be positive, which i assume is the correct return value.

Thanks! Have a nice day

**Comment by matrixise** [comment]
This repository is not about Python itself. If you think it's an issue about Python, open an issue on https://bugs.python.org

**Comment by Xenox-Inno** [comment]
Thanks Stéphane.
