### ISSUE TITLE
Request: removal of me from add_to_nosy on Cross-build component

### ISSUE THREAD

**Issue by moreati** [python/psf-infra-meta#135]
On https://bugs.python.org/component my bpo account Alex.Willmer is listed in add_to_nosy for component 28 (Cross-Build). I would to be removed, but it appears there's no web UI to do so, or its something I lack permission to do.

Please could you remove me, apoologies if this is the wrong avenue to make this request.

**Comment by ezio-melotti** [comment]
I now removed you from the `add_to_nosy` for `Cross-Build`.
