### ISSUE TITLE
Context manager does not update frame line number on exit

### ISSUE THREAD

**Issue by asaboor-gh** [python/psf-infra-meta#136]
When you use a context manager, you can collect code block inside it based on line number in `sys._getframe().f_back.f_lineno` and `linecache.getlines(file)`. For example

```python
with some_context():
    # At this point line number is N
    do_something()
    # exit line number is M
```
Before 3.10, `M = N +2` holds but in 3.10 it is `M = N`. Is it a bug or new design?

**Comment by matrixise** [comment]
Please, this repo is not related to Python itself. If you think it's a bug, open an issue on https://bugs.python.org
