### ISSUE TITLE
多重继承问题：super中传一个多重继承的类，只能识别到第一个

### ISSUE THREAD

**Issue by ipmshen** [python/psf-infra-meta#139]
问题描述：
B继承A，Y继承Z，BY继承B和Y，那么BY中的super只能代表B（如果是YB则只能代表Y），希望是可以super可以代表BY，代码如下：
class SkillMixin(object):
    def __init__(self,skillName):
        self.skillName = skillName
class BasketballMixin(SkillMixin):
    def __init__(self,skillName):
        super(BasketballMixin,self).__init__(skillName)
        
class Person(object):
    def __init__(self,name,gender):
        self.name = name
        self.gender = gender
class Student(Person):
    def __init__(self,name,gender,score):
        super(Student, self).__init__(name, gender)
        self.score = score

class BasketballStudent(Student,BasketballMixin,):
    def __init__(self,name,gender,score,skillName):
        super(BasketballStudent,self).__init__(name,gender,score,skillName)
        
bs = BasketballStudent('basketboy','man',59,'basketball')
print(bs.name,bs.skillName)

**Comment by matrixise** [comment]
Sorry, but this tracker is not for Python itself. Please use the right Mailing list for that. https://discuss.python.org/
