### ISSUE TITLE
Restore b.p.o mail address in tracker emails

### ISSUE THREAD

**Issue by ezio-melotti** [python/psf-infra-meta#15]
Before emails sent from the tracker whenever someone created or edited an issue came from <report@bugs.python.org>, whereas now the sender (and the reply-to) is <cpython@roundup.psfhosted.org>.
This breaks email filters.

**Comment by ewdurbin** [comment]
Resolving this is in progress! Thanks for noting. I'll update as it "develops"

**Comment by ewdurbin** [comment]
I believe this is resolved, and the mail gateway is working properly now :)
