### ISSUE TITLE
registration: Invalid URL Scheme

### ISSUE THREAD

**Issue by mroutis** [python/psf-infra-meta#18]
I'm trying to create an account on: https://bugs.python.org/user?@template=register

To complete the registration, I access the URL on the confirmation email: https://bugs.python.org/?@action=confrego&otk=xxx

:warning: _I've replaced the `otk` value with `xxx` (I'm assuming this is something private)_

And the following message appears:
![2019-01-28-18 20 18](https://user-images.githubusercontent.com/7363250/51875177-8f84ff00-2329-11e9-93d0-cfabac938734.png)

**Comment by jeeger** [comment]
Same problem here.

**Comment by ewdurbin** [comment]
Thanks for your report, I'm unable to reproduce, but am getting a different error stating an invalid OTK.

I'll dig in later today, sorry for delay.

**Comment by yash1th** [comment]
Also facing the same problem, the registration is not getting completed because of this issue

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/6474295/53291771-7414e480-376d-11e9-95e9-0589a224803f.png">

Any update on this issue?

**Comment by mroutis** [comment]
It was the information I was adding on the homepage: `mroutis.com` instead of `https://mroutis.com`, never thought that `homepage` was the homepage field :sweat_smile: !

**Comment by jeeger** [comment]
Thanks, this fixed it. Maybe add validation to the registration field?

**Comment by shihai1991** [comment]
I meet this probleam too.
![image](https://user-images.githubusercontent.com/9103416/58385356-c3dfa200-8021-11e9-84e6-63e5d718683d.png)
