### ISSUE TITLE
Rename jason.coombs back to jaraco

### ISSUE THREAD

**Issue by jaraco** [python/psf-infra-meta#19]
When I became a core contributor, I was forced to change my bugs.python.org username to `jason.coombs`, despite the fact that name is more ambiguous and less direct than my primary online moniker, `jaraco`. At the time, the policy was that all new core developers would get a standard `first.last` username without exception.

Since then, we've moved to GitHub, where my username is `jaraco`, so now my username no longer matches across systems. Additionally, it appears that other core contributors have since been added without this username restriction.

Would you please rename my account back to `jaraco`?

**Comment by ewdurbin** [comment]
Done.
