### ISSUE TITLE
Enable dynamic compression at Fastly edge for d.p.o

### ISSUE THREAD

**Issue by methane** [python/psf-infra-meta#2]
Currently, contents of docs.python.org are not compressed.

Instead of using nginx gzip_static module, Fastly provides nice option.
https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping

How about just enabling it?

**Comment by methane** [comment]
Ping.

**Comment by ewdurbin** [comment]
done! let's see how it goes :)

**Comment by methane** [comment]
Thanks!
I confirmed that https://docs.python.org/3/tutorial/index.html is reduced from 26858 bytes to 5851 bytes.
