### ISSUE TITLE
mail.python.org SMTP down

### ISSUE THREAD

**Issue by pitrou** [python/psf-infra-meta#21]
It seems that mail.python.org currently doesn't accept any incoming connection on ports 25 and 587.  It's still pingable though. I've tried from three different hosts on different networks.

```
$ telnet mail.python.org 587
Trying 188.166.95.178...
Trying 2a03:b0c0:2:d0::71:1...
telnet: Unable to connect to remote host: Network is unreachable
$ telnet mail.python.org 25
Trying 188.166.95.178...
Trying 2a03:b0c0:2:d0::71:1...
telnet: Unable to connect to remote host: Network is unreachable
```

@ewdurbin

**Comment by ewdurbin** [comment]
It is: https://status.python.org

**Comment by pitrou** [comment]
Ah, sorry, I had forgotten about the status page.
