### ISSUE TITLE
Unable to complete registration

### ISSUE THREAD

**Issue by ddevault** [python/psf-infra-meta#23]
After clicking the registration confirmation link I received by email, I'm greeted with this page:

https://sr.ht/8GUk.png

My account is ddevault and my email address is sir@cmpwn.com.

**Comment by jcrben** [comment]
I had the same issue. It was due to me putting this in the homepage url field:
bencreasy.com

when it wanted me to put:
http://bencreasy.com

I redid the registration and it worked.

**Comment by ewdurbin** [comment]
Ref: #47
