### ISSUE TITLE
Python fails to compile due to modules not found (binascii, dateutil, pip, ...)

### ISSUE THREAD

**Issue by willie-lopez** [python/psf-infra-meta#28]
Hopefully this is the appropriate place to ask for help about this problem with building Python. I have already looked through numerous discussions about this and cannot find a solid answer to resolving it. Any help is appreciated!

When installing Python-2.7.16 on CentOS 6 and 7, I get a failure during the build for missing modules/packages. Other discussions advise to install pip. PIP, even with get-pip.py fails. I used -d to try and get some debugging information, but nothing useful came out of it. 

Even with just the basics:
./configure --prefix=$HOME/tools [--with-ensurepip][=true], the config seems to work fine. But the compile fails.  The build/compile fails with the following:
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _tkinter           bsddb185        
dl                 imageop            sunaudiodev     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
_multiprocessing   binascii           zlib            

It's as though Python make is not compiling the modules, because the source is there:
**[builduser@cdaac-test-7 Python-2.7.16]$ find . -name binascii*
./Doc/library/binascii.rst
./Modules/binascii.c
./build/temp.linux-x86_64-2.7/home/builduser/Python-2.7.16/Modules/binascii.o**

Trying to install pip fails as follows:
[builduser@cdaac-test-7 bin]$ ./python -d get-pip.py 
Traceback (most recent call last):
  File "get-pip.py", line 28, in <module>
    import tempfile
  File "/home/builduser/rpm/tools/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/home/builduser/rpm/tools/lib/python2.7/random.py", line 48, in <module>
    from binascii import hexlify as _hexlify
ImportError: No module named binascii

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
