### ISSUE TITLE
 blog.python.org in HTTPS doesn't provide a server certificate?

### ISSUE THREAD

**Issue by vstinner** [python/psf-infra-meta#3]
Firefox simply doesn't let me open https://blog.python.org/ It seems like this website doesn't provide any server certificate!? First time that I see such issue.

OpenSSL output:

```
haypo@selma$ openssl s_client -connect blog.python.org -port 443
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 254 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1507063145
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

Compare it to a "normal" website like python.org (cert truncated):

```
haypo@selma$ openssl s_client -connect www.python.org -port 443
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server CA
verify return:1
depth=0 businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, serialNumber = 3359300, street = 16 Allen Rd, postalCode = 03894-4801, C = US, ST = New Hampshire, L = Wolfeboro, O = Python Software Foundation, CN = www.python.org
verify return:1
---
Certificate chain
 0 s:/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=New Hampshire/L=Wolfeboro/O=Python Software Foundation/CN=www.python.org
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIII9TCCB92gAwIBAgIQBfUWINUHHM+XBay/kaGttjANBgkqhkiG9w0BAQsFADB1
(...)
lBvRRs8wTczjbK0lSDJIG19bfMn5Xe7UXb5aMpt6FMKIxZmsfo1ys5I=
-----END CERTIFICATE-----
subject=/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=New Hampshire/L=Wolfeboro/O=Python Software Foundation/CN=www.python.org
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4168 bytes and written 380 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: C5836DCD75C9CF0D28E2BE12E7C88127C9117B8040297D754F2DAAB6BE7E35DC
    Session-ID-ctx: 
    Master-Key: AA060ED554834BE38533E53FD2B05AFC1C3B0E847F1D955D5B747A4F8BBEF5296B740C6C967D2A6E2BBF4C9AEEAE97CF
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 1200 (seconds)
    TLS session ticket:
    0000 - c9 e7 0b 1c 34 bc 42 af-85 4f 61 3c bc 65 48 87   ....4.B..Oa<.eH.
    0010 - 42 bf 76 fa 19 05 66 03-04 5c b2 fb bd 84 7c f2   B.v...f..\....|.
    0020 - 82 b8 c6 f9 69 11 ce d0-b8 9b d3 60 8e 37 3c 5f   ....i......`.7<_
    0030 - ba 61 5a 57 ed b9 98 65-33 e8 60 cd 2d 44 f2 93   .aZW...e3.`.-D..
    0040 - e5 c3 e5 d0 a0 3d 0c 12-64 06 92 cf 84 19 92 6b   .....=..d......k
    0050 - 72 6c 4e 24 56 5d 75 22-ed e2 4f 08 6c 53 35 fd   rlN$V]u"..O.lS5.
    0060 - be 73 f8 c2 da 18 22 d2-29 59 b3 46 5a c0 22 4a   .s....".)Y.FZ."J
    0070 - 0a cc b5 5f f7 11 21 99-ff bb b9 26 73 44 63 a6   ..._..!....&sDc.
    0080 - 19 78 95 6d f5 9d 23 f1-ac 21 33 b5 6b b3 68 d9   .x.m..#..!3.k.h.
    0090 - 21 ee 6f a9 4a b2 d1 04-86 83 06 e6 7f e5 77 62   !.o.J.........wb

    Start Time: 1507063135
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

DONE
```

Note: I first reported the issue at https://github.com/python/pythondotorg/issues/1159 but it was closed since it was the wrong issue tracker.

**Comment by haypo** [comment]
@berkerpeksag suggested me to ping @MarkMangoba :-)

**Comment by timm3** [comment]
This issue is affecting me as well. Can a general ETA be given for https support of this sub-domain?

**Comment by ewdurbin** [comment]
blog.python.org is hosted on Blogger/blogspot. TLS for custom domains is a not a feature they offer at this time.

We have the option of fronting this domain with Fastly, but I'm not sure what the implications are there for any traffic/view metrics.

@benjaminp @ned-deily it looks like the release manager role is the most common role posting on this site, are any of the traffic metrics in blogger/blogspot valuable to you? if not ensuring that [tls is enabled](https://blogger.googleblog.com/2015/09/https-support-coming-to-blogspot.html) and letting me know what the blogspot domain is, we can throw the CDN in front of it more or less whenever we feel like it.

@MarkMangoba @benjaminp if one of you could add my google user (ewdurbin@gmail.com) to the blogger for blog.python.org I can push this through.

**Comment by vstinner** [comment]
Would it be possible to only serve the blog on HTTP if HTTPS is not doable?

**Comment by benjaminp** [comment]
I sent you the invitation, ewdurbin.

I don't think simply redirecting `blog.python.org` to a HTTPS site is too criminal.

**Comment by ewdurbin** [comment]
thanks for the invite @benjaminp, but unfortunately it doesn't looks like have access to the settings necessary. TLS/HTTPS and redirect settings are normally in this tab, but all I see is 
<img width="555" alt="screen shot 2017-12-13 at 9 53 35 am" src="https://user-images.githubusercontent.com/1200832/33944916-88c51d94-dfeb-11e7-8077-7de66f4107a1.png">

**Comment by benjaminp** [comment]
Yeah, unfortunately, you can't change the user role until they've
accepted the invitation.

**Comment by ewdurbin** [comment]
Thanks! I’m gonna attempt the swap to TLS via Fastly over the weekend.

**Comment by ewdurbin** [comment]
Initial work is done... still kinda goofy since we can't get blogger to simultaneously accept the `blog.python.org` hostname _and_ accept TLS connections of any kind :/

So this means links and such are now pointing to `pythoninsider.blogspot.com`... but at least they're HTTPS.

**Comment by ewdurbin** [comment]
TLS, Redirects, Links, Feed URLs, etc are all now fixed up with a little template editing and JS. marking as closed.

**Comment by ewdurbin** [comment]
Reference material used:
  - https://www.bloggerguider.com/2016/08/https-ssl-for-blogger-custom-domains.html
  - https://www.electronicsdiary.com/2017/10/https-for-blogger-custom-domain.html
