### ISSUE TITLE
IDLE not starting 

### ISSUE THREAD

**Issue by Divyansh-programmer** [python/psf-infra-meta#32]
Idle is not starting(python 3.7), though python is starting in cmd on Windows 8.1 pro 
I also typed import idlelib.idle, Then also its not opening
Please help me

**Comment by michaelion** [comment]
Had same problem with launching IDLE in Windows 10 after downloading Python 3.7.4 yesterday.  
When I run python -m idlelib

File "C:\Users\Michaelion|AppData\Local\Programs\Python|Python37-32\lib\tkinter\_init_.py", line 2023, in _init_tkinter.TclError: Can't find usuable init.tcl in the following directories: ....

This probably means that Tcl wasn't installed properly.

Downloaded multiple times, found something about file path being incorrect, but insure how to correct.  Uninstalled & re-installed couple of times, same error each time.

**Comment by Divyansh-programmer** [comment]
Thanks , but now it is solved

**Comment by michaelion** [comment]
Great to hear that you got it to work, I was able to get mine to work as well.  I copied & pasted both the init.tcl & tk.tcl then placed them in the Lib folder as their was already a path to look for it in that folder.  This solved the problem I had with IDLE not opening.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
