### ISSUE TITLE
How to filter the Python bugtracker?

### ISSUE THREAD

**Issue by disconnect3d** [python/psf-infra-meta#39]
Hey,

Sorry if that is documented somewhere but is there any option to filter the search in Python bugtracker?

For example I would like to be able to find all open security or performance issues.

I know that many issues are missing e.g. type labels or that it is possible to group or sort issues but that's a bit different as one have to play with URI query parameters to find proper page to start digging through ;).

**Comment by rouilj** [comment]
1. Choose Issue Search from the left hand menu
2. In the form choose "security" (o performance) from the type drop down menu and  choose status: open or status: not closed
3. Click the search button at the bottom of the form

**Comment by disconnect3d** [comment]
Thanks! No idea how I missed that :P.
