### ISSUE TITLE
Segmentation fault: 11  - Python 3.6 on Macbook

### ISSUE THREAD

**Issue by honglou2001** [python/psf-infra-meta#44]
Process:               Python [5343]
Path:                  /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               3.6.5 (3.6.5)
Code Type:             X86-64 (Native)
Parent Process:        bash [3524]
Responsible:           Python [5343]
User ID:               501

Date/Time:             2019-10-15 13:26:45.395 +0800
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Anonymous UUID:        4552DCD6-6528-6E1A-0C86-24A09F7835F8

Time Awake Since Boot: 9600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000201c49b57
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [5343]

VM Regions Near 0x201c49b57:
    VM_ALLOCATE            0000000181c4a000-0000000181c4b000 [    4K] r-x/rwx SM=PRV  
--> 
    __UNIXSTACK            00007fff5b000000-00007fff5c000000 [ 16.0M] rw-/rwx SM=ALI  /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python

Application Specific Information:
dyld: launch, running initializers
/Library/Application Support/Cylance/Desktop/CyMemDef.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x0000000201c49b57 0 + 8619596631
1   CyMemDef.dylib                	0x0000000100a77737 _vm_protect(unsigned int, unsigned long, unsigned long, unsigned int, int) + 149
2   CyMemDef.dylib                	0x0000000100a73e3e mach_override_setup + 219
3   CyMemDef.dylib                	0x0000000100a79297 injector(inject_s*, unsigned long) + 355
4   CyMemDef.dylib                	0x0000000100a790a5 MemDefMemory_initialize() + 35
5   CyMemDef.dylib                	0x0000000100a77050 memdefosx_initialize + 28
6   dyld                          	0x00007fff5f67dcc8 ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 518
7   dyld                          	0x00007fff5f67dec6 ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
8   dyld                          	0x00007fff5f6790da ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 358
9   dyld                          	0x00007fff5f67906d ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 249
10  dyld                          	0x00007fff5f678254 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 134
11  dyld                          	0x00007fff5f6782e8 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 74
12  dyld                          	0x00007fff5f667774 dyld::initializeMainExecutable() + 199
13  dyld                          	0x00007fff5f66c78f dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6237
14  dyld                          	0x00007fff5f6664f6 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 1154
15  dyld                          	0x00007fff5f666036 _dyld_start + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000100a94178  rbx: 0x0000000101c4ab3a  rcx: 0x0000000000000000  rdx: 0x0000000000000008
  rdi: 0x0000000000000103  rsi: 0x0000000101c4ab3a  rbp: 0x00007fff5bffdef0  rsp: 0x00007fff5bffdaa8
   r8: 0x0000000000000005   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000005  r13: 0x0000000000000103  r14: 0x0000000000000000  r15: 0x0000000000000008
  rip: 0x0000000201c49b57  rfl: 0x0000000000010246  cr2: 0x0000000201c49b57
  
Logical CPU:     1
Error Code:      0x00000014
Trap Number:     14

Binary Images:
       0x100000000 -        0x100000ff7 +org.python.python (3.6.5 - 3.6.5) <C539EB14-B454-D151-7B93-6A12255582B2> /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
       0x100003000 -        0x100450fe7  com.apple.CoreFoundation (6.9 - 1560.12) <B5BDC307-6C89-3DE0-B4B9-4C2C650E4528> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1006fb000 -        0x100922fef +org.python.python (3.6.5, [c] 2001-2018 Python Software Foundation. - 3.6.5) <EBF198CD-A37E-A0F1-1E7C-19B9F912D34A> /Library/Frameworks/Python.framework/Versions/3.6/Python
       0x100a6b000 -        0x100a6cffb  libSystem.B.dylib (1252.200.5) <D5AFCC78-2AC2-37EB-B0EF-BB00FD38ED00> /usr/lib/libSystem.B.dylib
       0x100a72000 -        0x100a83ff7 +CyMemDef.dylib (0) <7F2E0690-20B4-335A-AE40-D51A0FD1582F> /Library/Application Support/Cylance/*/CyMemDef.dylib
       0x100ab5000 -        0x10123bfe7  libobjc.A.dylib (750.1) <9CE27EC3-3A12-35D1-8F2F-3550B9668259> /usr/lib/libobjc.A.dylib
       0x1013f3000 -        0x1013f4ff7  libDiagnosticMessagesClient.dylib (107) <C542CB3C-AA44-3D7F-B88C-79CC31B481AB> /usr/lib/libDiagnosticMessagesClient.dylib
       0x1013fa000 -        0x10165dffb  libicucore.A.dylib (62108.0.1) <969815D4-A345-31BB-82B7-0C3B58CA7E90> /usr/lib/libicucore.A.dylib
       0x10174b000 -        0x10175dffb  libz.1.dylib (70.200.4) <99A3D725-8388-38B4-B66C-5E9006E6F072> /usr/lib/libz.1.dylib
       0x101763000 -        0x101778fff  libc++abi.dylib (400.17) <BA948A32-9024-3E55-98D4-18E31F6AED25> /usr/lib/libc++abi.dylib
       0x10178f000 -        0x1017e6ff7  libc++.1.dylib (400.9.4) <D4AB366F-48A9-3C7D-91BD-41198F69DD57> /usr/lib/libc++.1.dylib
       0x101847000 -        0x10184bff3  libcache.dylib (81) <FE21A7E9-DBEB-33AC-836B-785AD036ACF4> /usr/lib/system/libcache.dylib
       0x101851000 -        0x10185bff3  libcommonCrypto.dylib (60118.220.1) <1099E427-6E81-3059-87AF-6F5FD81CA998> /usr/lib/system/libcommonCrypto.dylib
       0x101869000 -        0x101870fff  libcompiler_rt.dylib (63.4) <A4D9CF37-D076-3CE9-95F1-DA89DA1601B6> /usr/lib/system/libcompiler_rt.dylib
       0x10187e000 -        0x101887ff3  libcopyfile.dylib (146.200.3) <4BCDADBF-79F5-3829-B47D-64DA0D44BCBF> /usr/lib/system/libcopyfile.dylib
       0x10188e000 -        0x101912fdf  libcorecrypto.dylib (602.220.6) <E1046E01-A2FD-35B4-B018-ACC372F3880E> /usr/lib/system/libcorecrypto.dylib
       0x10192f000 -        0x101969ff7  libdispatch.dylib (1008.220.2) <D8B56783-152A-34A8-94E9-8E6BAE049384> /usr/lib/system/libdispatch.dylib
       0x10199a000 -        0x1019c9fff  libdyld.dylib (635.2) <1B79A5CE-125F-301F-A441-C1869573AED0> /usr/lib/system/libdyld.dylib
       0x1019ec000 -        0x1019ecffb  libkeymgr.dylib (30) <A73AA788-C35C-3284-BFCA-95B1BBDF0CF3> /usr/lib/system/libkeymgr.dylib
       0x1019f1000 -        0x1019f1ff7  liblaunch.dylib (1336.220.5) <95EB6EAF-2DC5-344F-BADB-CA4E35E4E503> /usr/lib/system/liblaunch.dylib
       0x1019f8000 -        0x1019fdfff  libmacho.dylib (921) <ECC4E97C-575E-3A08-8191-BF02D7D4E637> /usr/lib/system/libmacho.dylib
       0x101a04000 -        0x101a06ffb  libquarantine.dylib (86.220.1) <6AE5AEEC-A9FD-3CF8-92DD-12B5AFBE12DE> /usr/lib/system/libquarantine.dylib
       0x101a0d000 -        0x101a0eff3  libremovefile.dylib (45.200.2) <D74A307B-3DC7-3992-B16C-DACB8207BE13> /usr/lib/system/libremovefile.dylib
       0x101a14000 -        0x101a2bff3  libsystem_asl.dylib (356.200.4) <EC9D8AD4-E5CB-3765-804A-9E1E9DC045D2> /usr/lib/system/libsystem_asl.dylib
       0x101a39000 -        0x101a39fff  libsystem_blocks.dylib (73) <26419398-C30C-30F1-B656-A92AFA9560F6> /usr/lib/system/libsystem_blocks.dylib
       0x101a3e000 -        0x101ac6fff  libsystem_c.dylib (1272.200.26) <3DEEE96E-6DF6-35AD-8654-D69AC26B907B> /usr/lib/system/libsystem_c.dylib
       0x101aef000 -        0x101af2ff7  libsystem_configuration.dylib (963.200.27) <02CC3996-B34E-333C-8806-AE2699D34424> /usr/lib/system/libsystem_configuration.dylib
       0x101af9000 -        0x101afcff7  libsystem_coreservices.dylib (66) <254B6849-2C8F-302C-8616-B8324A11AB30> /usr/lib/system/libsystem_coreservices.dylib
       0x101b02000 -        0x101b08ffb  libsystem_darwin.dylib (1272.200.26) <974E9EF7-DE72-34B7-B056-0A81C10DF8EB> /usr/lib/system/libsystem_darwin.dylib
       0x101b13000 -        0x101b19ff7  libsystem_dnssd.dylib (878.200.35) <FFC665AA-B257-35AD-BD8B-32FD42C2EEC1> /usr/lib/system/libsystem_dnssd.dylib
       0x101b1f000 -        0x101b6bff3  libsystem_info.dylib (517.200.9) <0707C387-D7DE-372E-8FF1-3DE5C91932D6> /usr/lib/system/libsystem_info.dylib
       0x101b82000 -        0x101bcdff7  libsystem_m.dylib (3158.200.7) <43D1796B-954F-37D6-B1AC-9D80DF0655A2> /usr/lib/system/libsystem_m.dylib
       0x101bdc000 -        0x101c00ff7  libsystem_malloc.dylib (166.220.1) <3B196122-4E0D-3E3F-AA3E-5115B976DE26> /usr/lib/system/libsystem_malloc.dylib
       0x101c0f000 -        0x101c1aff3  libsystem_networkextension.dylib (767.220.1) <C54EB8F6-F305-3452-8DB1-F7DA6859AF8C> /usr/lib/system/libsystem_networkextension.dylib
       0x101c27000 -        0x101c2efff  libsystem_notify.dylib (172.200.21) <BCCB222F-DC64-3954-A836-DCCE6659CA5A> /usr/lib/system/libsystem_notify.dylib
       0x101c35000 -        0x101c38ff7  libsystem_sandbox.dylib (851.220.9) <4D6433A8-C703-3ED9-82EB-B9E481A0FD2F> /usr/lib/system/libsystem_sandbox.dylib
       0x101c3f000 -        0x101c41ff3  libsystem_secinit.dylib (30.220.1) <6C681113-8C48-3256-BEF6-0C3723DEB926> /usr/lib/system/libsystem_secinit.dylib
       0x101c47000 -        0x101c6eff7  libsystem_kernel.dylib (4903.221.2) <0E882078-7330-3B49-AA5D-3CDB5645A4E5> /usr/lib/system/libsystem_kernel.dylib
       0x101c89000 -        0x101c92fef  libsystem_platform.dylib (177.200.16) <B75B04AD-69FE-3ADE-84D2-C17972FC8F49> /usr/lib/system/libsystem_platform.dylib
       0x101c9b000 -        0x101ca5fff  libsystem_pthread.dylib (330.220.2) <4958273C-4273-3501-8137-E44249E10D9C> /usr/lib/system/libsystem_pthread.dylib
       0x101cb0000 -        0x101cb7ff7  libsystem_symptoms.dylib (820.227.2) <3147D594-F41F-35FD-BF0B-6B8B66A407DE> /usr/lib/system/libsystem_symptoms.dylib
       0x101cbe000 -        0x101cd3ff7  libsystem_trace.dylib (906.220.1) <D5045DC5-A165-3238-A470-1796F12BF84F> /usr/lib/system/libsystem_trace.dylib
       0x101ce3000 -        0x101ce8ffb  libunwind.dylib (35.4) <41222EF6-2233-3CF4-947A-15D48CB8C030> /usr/lib/system/libunwind.dylib
       0x101cf0000 -        0x101d20fff  libxpc.dylib (1336.220.5) <B2137772-E202-3656-A089-F6DD517007D5> /usr/lib/system/libxpc.dylib
    0x7fff5f665000 -     0x7fff5f6e36a7  dyld (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26541
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=25.4M resident=0K(0%) swapped_out_or_unallocated=25.4M(100%)
Writable regions: Total=25.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=25.5M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        2 
MALLOC                            9260K        8 
MALLOC guard page                   16K        5 
VM_ALLOCATE                          4K        2 
__DATA                            4316K       59 
__LINKEDIT                        4768K       46 
__TEXT                            20.7M       48 
__UNICODE                          564K        2 
__UNIXSTACK                       16.0M        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             55.2M      167 

Model: MacBookPro14,1, BootROM 184.0.0.0.0, 2 processors, Intel Core i5, 2.3 GHz, 16 GB, SMC 2.43f6
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.9f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB 2.0 BILLBOARD
Thunderbolt Bus: MacBook Pro, Apple Inc., 39.2

**Comment by ewdurbin** [comment]
This issue tracker is for problems with services hosted by the PSF. This appears to be a bug report for Python itself, which should be filed at bugs.python.org.
