### ISSUE TITLE
bugs.python.org is blocked in Russian Federation

### ISSUE THREAD

**Issue by asvetlov** [python/psf-infra-meta#45]
Russian court issued a letter that bans `188.166.0.0/17` IP range to prevent access to some site.
The site is not related to Python at all.

Unfortunately, bugs.python.org is blocked too, it is resolved as `188.166.48.69`.
Could we change the public IP address of the host to unblock Russian people?

This is a link to the court judgment for the reference: https://mos-gorsud.ru/rs/taganskij/services/cases/civil/details/2cc72aea-39e7-4f8e-adc9-37d170966efa

I've asked guys from Russia, they said that much easier to update IP than convince the court to make an exception for `188.166.48.69` from `188.166.0.0/17` range.

Thanks.

**Comment by shagren** [comment]
Yes, it's true. `bugs.python.org` is not accessible from Russia. I have tried few different providers.

**Comment by ewdurbin** [comment]
Is there any way for us to ensure the new IP address isn't in a similarly banned range?

Updating the IP address for bugs.python.org is unfortunately not a trivial task. :/

**Comment by ewdurbin** [comment]
It appears this would also affect mail.python.org... can you confirm?

**Comment by asvetlov** [comment]
I'm living in Ukraine, here everything works fine.
@shagren can help with the check I guess.
Also, he knows much more about a registry of banned Russian addresses.

**Comment by grigoryvp** [comment]
Yes, the IP range is blocked in Russia, and unblocking it is a many-months legal process with unclear outcome, so moving to a new IP address sounds like a really good solution to make developers life better! We can use this official service to check if specified IP address is blocked: https://blocklist.rkn.gov.ru

**Comment by shagren** [comment]
> It appears this would also affect mail.python.org... can you confirm?
@ewdurbin is also unaccessible for me

**Comment by kurtgn** [comment]
Maybe just create a mirror for Russia? Something like m.bugs.python.org

That’s what we do when our servers get blocked :)

**Comment by dmig** [comment]
WTF guys?
It's not bugs.python.org been blocked, it's **you** who've been blocked! So don't ask others to solve your problems!
Either go to the court to argue with this, use VPN or change the country!

Childish...

**Comment by asvetlov** [comment]
@dmig your proposal is not constructive at all.

**Comment by dmitry-mukhin** [comment]
he's not wrong though.

**Comment by asvetlov** [comment]
This issue is not for immigration discussion or VPN usage, ok?
Do you personally get frustrated if bugs.python.org gets working from Russia without extra steps on your side?

**Comment by ud1** [comment]
Just use Tor browser. I use it at work every day (for example to download Intellij Idea or Soap UI).

**Comment by vir-mir** [comment]
By the way, I filed an application in RK, with a request to remove the lock. to which I received an answer.  it says here that this subnet was blocked due to the fact that there are telegram IP addresses.
They also hinted that we need to transfer bugs.python.org since they won’t remove the lock.

here is the official reply received by mail https://i.ibb.co/DwsHGZy/tg.jpg

**Comment by vnetserg** [comment]
> They also hinted that we need to transfer bugs.python.org since they won’t remove the lock.
I don't see this hint there. They just say that they won't unblock the address unless the provider (Digital Ocean?) prevents Telegram from operating on their IP addresses.

**Comment by brainwane** [comment]
Is this (not being able to access bugs.python.org or mail.python.org) still reproducible for users in the Russian Federation? I presume it is but I figured it's good to re-check, then ask for a decision from the infrastructure team.

**Comment by grigoryvp** [comment]
Yep, https://isitblockedinrussia.com/?host=bugs.python.org

**Comment by dogonthesun** [comment]
Good news everyone! bugs.python.org is unblocked now in Russian Federation.
Unfortunately, the cause is not related to bugs.python.org directly.
Please, check if your provider allows you to access to bugs.python.org and mail.python.org.

**Comment by shagren** [comment]
Works for me!

**Comment by asvetlov** [comment]
Cool!
