### ISSUE TITLE
bugs.python.org doesn't reply on IPv6 ping

### ISSUE THREAD

**Issue by vstinner** [python/psf-infra-meta#5]
Hi,

I can ping bugs.python.org on IPv4 but not IPv6. Is it on purpose?

I tried ping yesterday since the website was stuck in HTTP using IPv6, but worked on IPv4.

Victor

**Comment by ewdurbin** [comment]
https://github.com/python/psf-infra-meta/issues/6#issuecomment-348068915

**Comment by vstinner** [comment]
The AAAA record of the bugs.python.org domain has been removed, I close the issue.
