### ISSUE TITLE
SyntaxError: 'break' outside loop for legal Expression

### ISSUE THREAD

**Issue by elArch** [python/psf-infra-meta#52]
Why I can't execute this code:
```
while False:
    if False:
        break
print('WTF?')
```
When I use repl.it or PyCharm on my work all works fine, yes I know this code looks silly, but it is a legal expression.

About CPython Interpreter:
C:\WINDOWS\system32>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
