### ISSUE TITLE
registration confirmation e-mails

### ISSUE THREAD

**Issue by apparluk** [python/psf-infra-meta#55]
[Tracker-discuss] [issue584]

Registration confirmation emails never arrive, tested with multiple email hosts
_______________________________________________________

chesterR Sat, 02 Apr 2016 19:27:07 -0700

New submission from chesterR:

Attempted multiple times to register a new account on the python issue tracker, 
no confirmation email showed up in any of the email addresses I used after 
about 24 hours. Providers I was able to test include Gmail, AOL email, and 
Mailinator hotmail.

Also tried acquiring a new IP, to no success. Obviously, spam folders in all 
emails were checked as well.

messages: 3026
nosy: chesterR
priority: urgent
status: unread
title: Registration confirmation emails never arrive, tested with multiple 
email hosts
_______________________________________________________
PSF Meta Tracker <metatrac...@psf.upfronthosting.co.za>
<http://psf.upfronthosting.co.za/roundup/meta/issue584>
_______________________________________________________

SilentGhost Sat, 02 Apr 2016 23:07:24 -0700

SilentGhost added the comment:

I suspect it's the same problem as issue568

nosy: +SilentGhost
status: unread -> chatting
_______________________________________________________

Al Schapira Sat, 14 May 2016 11:32:42 -0700

Al Schapira added the comment:

Same problem here.  Never get confirmation email to complete.
Linux ADS2 4.4.8-200.fc22.i686 #1 SMP Wed Apr 20 19:11:01 UTC 2016 i686 i686 
i386 GNU/Linux

nosy: +schapira
_______________________________________________________

Eric Lindblad Wed, 12 Dec 2018 01:59:10 -0800

New submission from Eric Lindblad:

Filling in the non-highlighted fields (Name, GitHub Name, Organisation, 
Homepage) the registration confirmation email arrives.

https://bugs.python.org/user?@template=register

nosy: +eric.lindblad
_______________________________________________________

The correction of the code on the registration page still has not been done.

**Comment by Baljak** [comment]
Same here, I'm unable to create an account since I don't receive the confirmation email.

**Comment by apparluk** [comment]
@Baljak

If you fill in the 'GitHub Name' (a non-highlighted field) do you then receive the confirmation email?

These files had a variable fixed Jan 10, 2019; bug filed Sep 30, 2018.

.azure-pipelines/windows-appx-test.yml
.azure-pipelines/windows-steps.yml
PCbuild\build.bat

**Comment by Baljak** [comment]
@apparluk No I don't receive it... I always filled the GitHub Name field actually.

**Comment by apparluk** [comment]
From the bot comment near the top of your other linked to issue, it appears that for a GH user's merge to go through, b.p.o. does a search of GH user names, that doesn't infer that to register for a b.p.o. account the provision of a GH user name is required, _i.e._, the inference is that registration for a b.p.o. account might occur simply for the purpose of submitting a bug report, where the submitter has no intention of contributing (in this instance, via a merge) to the cpython GH hosted source code.

The bug report which resulted in the build variables fix was filed by one individual and the merge itself by another.

As you've reported filling in the non-highlighted GH user name field had not on several occasions resulted in your receipt of the confirmation email, and as reported in the opening of this current issue the filling in all non-highlighted fields worked on Wed, 12 Dec 2018.

Presently then one might be inclined towards the opinion that a component (or perhaps several components) of the b.p.o.  registration system is intermittently not functional, and - if that was not the case or not applicable at the time of your attempts - that filling in additional (perhaps all) non-highlighted fields might result in the confirmation email being received.

<hr>

I've read that Windows-native C++ and Python (when used together) should use the same C/C++ compiler, I don't have a citation here for that, but presume those concerned with your other cited GH ticket are cognisant of that information.

**Comment by apparluk** [comment]
@Baljak 

If you're inclined to try filling in among the non-highlighted fields solely the 'Name' field to see if that results in the the confirmation email being received, let me know in the next week or so.

Otherwise at this point of time my sympathies are to close this issue.
