### ISSUE TITLE
Incorrect complex number inference

### ISSUE THREAD

**Issue by anjali411** [python/psf-infra-meta#59]
>>> 1/2j
-0.5j

Expected: 0.5j

there's probably a bug in the way string is being parsed. 1/2j is probably being parsed a s 1 / 2j instead of (1/2) j

Also this doesn't work
>>> (1/2)j
  File "<stdin>", line 1
    (1/2)j
         ^
SyntaxError: invalid syntax

**Comment by mdickinson** [comment]
This is the wrong place to report suspected Python bugs. https://bugs.python.org is the right place. (But FWIW, this isn't a Python bug.)

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
