### ISSUE TITLE
bugs.python.org is unreachable in IPv6

### ISSUE THREAD

**Issue by vstinner** [python/psf-infra-meta#6]
Hi,

The bugs.python.org server doesn't reply on IPv6 on tcp/443: I see "SYN_SENT" and then... nothing...

Example:

```
vstinner@apu$ nc -6 -vv bugs.python.org 443
Ncat: Version 7.60 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
NCAT DEBUG: Unable to load trusted CA certificates from /usr/share/ncat/ca-bundle.crt: error:02001002:system library:fopen:No such file or directory
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_tcp(): TCP connection requested to 2a01:4f8:131:2480::3:443 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT TIMEOUT for EID 8 [2a01:4f8:131:2480::3:443]
Ncat: Connection timed out.
```

I found this issue while trying to query the XML-RPC of bugs.python.org. My code uses a xmlrpc.client.ServerProxy('https://bugs.python.org/xmlrpc', allow_none=True) object, which later calls socket.create_connection(('bugs.python.org', 443)) and this call hangs "forever".

See also issue #5:  bugs.python.org doesn't reply on IPv6 ping.

**Comment by ewdurbin** [comment]
Clear that the AAAA record isn’t set for the right address, so it was removed. TTL was 24 hours.

If we determine there is a good IPv6 address in the future we can set it once more.

**Comment by vstinner** [comment]
The AAAA record of the bugs.python.org domain has been removed, I close the issue.
