### ISSUE TITLE
Two smallest ticks of symlog axis do not respond to the usetex=True

### ISSUE THREAD

**Issue by AbinashKumarShaw** [python/psf-infra-meta#64]
I'm trying to plot data in some files using subplots. I need to use the symlog for the y-axis as well as I'm also using the pyplot.rc('text,'usetex=True) to write everything in mathematics font. However it turned out that the smallest two tick labels on the symlog axes do not change to the math font.

My script is as follows,
#-----------------------------------------------------------------------------------------------------------#
import numpy as np
import matplotlib.pyplot as plt

z=[13,11,10,9,8,7]
xx=np.linspace(0.01,10,3,endpoint=True)
horiz_line_data = np.array([0 for i in range(len(xx))])
x=np.loadtxt('Pk_Rmfp_avg_7.derivative')[:,0]
fig, ax = plt.subplots(nrows=3, ncols=6, sharex=True, sharey='row', edgecolor='k',figsize=(12,8))
plt.xscale('log')
plt.rc('axes', linewidth=10)
plt.xlim([0.03,5])
plt.rc('text',usetex=True)

for k in range(6):
        y1=np.loadtxt('Pk_M_avg_'+str(z[k])+'.derivative')[:,1]
        y2=np.loadtxt('Pk_Nion_avg_'+str(z[k])+'.derivative')[:,1]
        y3=np.loadtxt('Pk_Rmfp_avg_'+str(z[k])+'.derivative')[:,1]
        #---------------------------------------------------#
        ax[0,k].set_yscale('symlog')
        ax[0,k].tick_params(axis='both', which= 'major',direction='in', length= 7, width=1.5,labelsize=18)
        ax[0,k].tick_params(axis='both', which= 'minor',direction='in', length= 4, width=1.5,labelsize=18)
        ax[0,k].plot(x, y1*x**3.0,linewidth=3, color='blue')
        ax[0,k].plot(xx,horiz_line_data,'r--',linewidth=1.5)
        ax[0,k].xaxis.set_ticks_position('both')
        ax[0,k].yaxis.set_ticks_position('both')
        ax[0,k].fill_between(xx,-1, 1, facecolor='yellow', edgecolor='none', linestyle=':', alpha=0.5)
        ax[0,k].set_ylim([-50,100])
        #------------------------------------------------------#
        ax[1,k].set_yscale('symlog')
        ax[1,k].tick_params(axis='both', which= 'major',direction='in', length= 7, width=1.5,labelsize=18)
        ax[1,k].tick_params(axis='both', which= 'minor',direction='in', length= 4, width=1.5,labelsize=18)
        ax[1,k].plot(x,y2*x**3.0,linewidth=3, color='blue')
        ax[1,k].plot(xx,horiz_line_data,'r--',linewidth=1.5)
        ax[1,k].xaxis.set_ticks_position('both')
        ax[1,k].yaxis.set_ticks_position('both')
        ax[1,k].fill_between(xx,-1, 1, facecolor='yellow', edgecolor='none', linestyle=':', alpha=0.5)
        ax[1,k].set_ylim([-150,150])
        #---------------------------------------------------#
        ax[2,k].set_yscale('symlog')
        ax[2,k].tick_params(axis='both', which= 'major',direction='in', length= 7, width=1.5,labelsize=18)
        ax[2,k].tick_params(axis='both', which= 'minor',direction='in', length= 4, width=1.5,labelsize=18)
        ax[2,k].plot(x,y3*x**3.0,linewidth=3, color='blue')
        ax[2,k].plot(xx,horiz_line_data,'r--',linewidth=1.5)
        ax[2,k].xaxis.set_ticks_position('both')
        ax[2,k].yaxis.set_ticks_position('both')
        ax[2,k].fill_between(xx,-1, 1, facecolor='yellow', edgecolor='none', linestyle=':', alpha=0.5)
        ax[2,k].set_ylim([-15,20])
        #--------------------------------------------------#

plt.subplots_adjust(left=0.11, bottom=0.10, right=0.99, top=0.92, hspace=0.0,wspace=0.0)

fig.text(0.5, 0.015, r'$k \,({\rm Mpc}^{-1})$',size=18)
fig.text(0.02, 0.900, r'$\partial \Delta_b^2(k)/\partial \ln(M_{\rm{min}})$',size=15, rotation='vertical')
fig.text(0.02, 0.615, r'$\partial \Delta_b^2(k)/\partial \ln(N_{\rm{ion}})$',size=15, rotation='vertical')
fig.text(0.02, 0.355, r'$\partial \Delta_b^2(k)/\partial \ln(R_{\rm{mfp}})$',size=15, rotation='vertical')
fig.text(0.15,0.935,r'$z=13$',size=20)
fig.text(0.288,0.935,r'$z=11$',size=20)
fig.text(0.443,0.935,r'$z=10$',size=20)
fig.text(0.60,0.935,r'$z=9$',size=20)
fig.text(0.745,0.935,r'$z=8$',size=20)
fig.text(0.895,0.935,r'$z=7$',size=20)
plt.show()
#-----------------------------------------------------------------------------------------------------#

Below is a part of my plot which shows the bug.

![derv](https://user-images.githubusercontent.com/35565857/80204892-52500f80-8647-11ea-8440-d7eb31bf8ce3.png)

**Comment by E-Paine** [comment]
Please report this on the matplotlib project's [Github page](https://github.com/matplotlib/matplotlib/issues). Also, "psf-infra-meta" is a meta-tracker meaning it is (mainly) meant for reporting issues with the normal bug tracker found at [bugs.python.org](https://bugs.python.org).

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
