### ISSUE TITLE
make test only fails on test_imprtlib in python 3.8.2

### ISSUE THREAD

**Issue by bora2020** [python/psf-infra-meta#66]
~/Python-3.8.2$ `make test TESTOPTS="-v test_imprtlib" `

**THIS IS THE OUTPUT :** 

 CC='gcc -pthread' LDSHARED='gcc -pthread -shared    ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python -E ./setup.py  build
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers
INFO: Could not locate ffi libs and/or headers

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _lzma              
_sqlite3              _tkinter              _uuid              
readline              zlib                                     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd                
time                                                           

Failed to build these modules:
_ctypes                                                        

running build_scripts
copying and adjusting /home/madbora/Python-3.8.2/Tools/scripts/pydoc3 -> build/scripts-3.8
copying and adjusting /home/madbora/Python-3.8.2/Tools/scripts/idle3 -> build/scripts-3.8
copying and adjusting /home/madbora/Python-3.8.2/Tools/scripts/2to3 -> build/scripts-3.8
changing mode of build/scripts-3.8/pydoc3 from 644 to 755
changing mode of build/scripts-3.8/idle3 from 644 to 755
changing mode of build/scripts-3.8/2to3 from 644 to 755
renaming build/scripts-3.8/pydoc3 to build/scripts-3.8/pydoc3.8
renaming build/scripts-3.8/idle3 to build/scripts-3.8/idle3.8
renaming build/scripts-3.8/2to3 to build/scripts-3.8/2to3-3.8
./python  ./Tools/scripts/run_tests.py -v test_imprtlib
/home/madbora/Python-3.8.2/python -u -W default -bb -E -m test -r -w -j 0 -u all,-largefile,-audio,-gui -v test_imprtlib
== CPython 3.8.2 (default, May 8 2020, 12:29:32) [GCC 7.5.0]
== Linux-5.3.0-51-generic-x86_64-with-glibc2.27 little-endian
== cwd: /home/madbora/Python-3.8.2/build/test_python_16601
== CPU count: 8
== encodings: locale=UTF-8, FS=utf-8
Using random seed 5492883
0:00:00 load avg: 0.47 Run tests in parallel using 10 child processes
0:00:00 load avg: 0.47 [1/1/1] test_imprtlib failed
test test_imprtlib crashed -- Traceback (most recent call last):
  File "/home/madbora/Python-3.8.2/Lib/test/libregrtest/runtest.py", line 270, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
  File "/home/madbora/Python-3.8.2/Lib/test/libregrtest/runtest.py", line 221, in _runtest_inner2
    the_module = importlib.import_module(abstest)
  File "/home/madbora/Python-3.8.2/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.test_imprtlib'

== Tests result: FAILURE ==

1 test failed:
    test_imprtlib
0:00:00 load avg: 0.47
0:00:00 load avg: 0.47 Re-running failed tests in verbose mode
0:00:00 load avg: 0.47 Re-running test_imprtlib in verbose mode
test test_imprtlib crashed -- Traceback (most recent call last):
  File "/home/madbora/Python-3.8.2/Lib/test/libregrtest/runtest.py", line 270, in _runtest_inner
    refleak = _runtest_inner2(ns, test_name)
  File "/home/madbora/Python-3.8.2/Lib/test/libregrtest/runtest.py", line 221, in _runtest_inner2
    the_module = importlib.import_module(abstest)
  File "/home/madbora/Python-3.8.2/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test.test_imprtlib'

1 test failed again:
    test_imprtlib

== Tests result: FAILURE then FAILURE ==

1 test failed:
    test_imprtlib

1 re-run test:
    test_imprtlib

Total duration: 360 ms
Tests result: FAILURE then FAILURE
Makefile:1130: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
