### ISSUE TITLE
different returns of same code

### ISSUE THREAD

**Issue by archila1** [python/psf-infra-meta#68]
Hello everyone. i'm new here, so dunno how to find if this issue is already addressed, so i'll just copy my code here that i made while doing some katas at codewars.com
![bug](https://user-images.githubusercontent.com/61683940/81974870-37196400-9637-11ea-9f09-c4eb5e2b1389.PNG)
`from itertools import permutations
def next_bigger(n):
    

ans = 0
    N = str(n)
    q = [i for i in str(n)]
    numb = 2
    while True:
        if len(N) ==1:
            return -1
            break
        
        a = set(permutations(q[-numb:]))
        for i in a:
            w = int("".join(i))
            if w > int(N[-numb:]):
                ans = N[:-numb] + str(w)
            
        if int(ans) > n:
            return int(ans)
            break
        else:
            if numb == len(N):
                return -1
                break
            else:
                numb +=1
print(next_bigger(144))
            
       

    

`

well, the code itself is not something amazing, but thing is... in every few runs, it gives as return 414 or 441.

any ideas?

**Comment by archila1** [comment]
found what was causing it. it was because of set. sorry for wrong info

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this filing such issues.

I think that [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com) would be better channels to get support when you're facing such issues like these. :)
