### ISSUE TITLE
Bad TLS config

### ISSUE THREAD

**Issue by Darkspirit** [python/psf-infra-meta#7]
https://www.hardenize.com/report/bugs.python.org/1519081490#www_tls
https://www.hardenize.com/report/bugs.python.org/1519081490#email_tls
https://observatory.mozilla.org/analyze.html?host=bugs.python.org

(good: https://www.hardenize.com/report/python.org)

**Comment by ewdurbin** [comment]
@Darkspirit we're in the process of migrating bugs.python.org to new infrastructure that can support modern TLS settings. In the meantime, I'll leave this issue open to track and update when complete.

**Comment by ewdurbin** [comment]
TLS config is vastly improved with new infra, closing :)
