### ISSUE TITLE
error in a product

### ISSUE THREAD

**Issue by ENANEUS** [python/psf-infra-meta#70]
import math
d=(6635869816740560)*(81)*(16**(-1))
print(int(d))

When making that product in Python it returns a number that is not

**Comment by E-Paine** [comment]
Python evaluates `16 ** -1` to a float meaning that the result of the multiplications is also a float (hence why `print(d)` and `print(int(d))` give different outputs). The Python float is built using the C double and so is limited by the under-lying mantissa size. In the future please post such a problem to [bugs.python.org](https://bugs.python.org) as "psf-infra-meta" is a meta-tracker (mainly) meant for reporting issues with bugs.python.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
