### ISSUE TITLE
sweetviz analyze works fine in DOS mode but fails in python Idle 3.7.7  with error "sweetviz has no attribute 'analyze'

### ISSUE THREAD

**Issue by subramanianramajayam** [python/psf-infra-meta#73]

**Comment by E-Paine** [comment]
sweetviz is currently in beta and so it seems more likely that this is a sweetviz problem (which can be reported on the project's [Github page](https://github.com/fbdesignpro/sweetviz/issues)). If they believe this is an IDLE problem, please report it on [bugs.python.org](https://bugs.python.org) as "psf-infra-meta" is a meta-tracker meaning it is (mainly) meant for reporting issues with bugs.python. In future, please give more details and a step-by-step reproduction of the issue as it could be quite difficult to reproduce using only the title. Thanks

P.S. You didn't call the file "sweetviz.py" did you?

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
