### ISSUE TITLE
Problem with serial communication

### ISSUE THREAD

**Issue by JFR-Gabriel** [python/psf-infra-meta#75]
I was doing a small serial communication system using pyserial. when I done the script on a .py file, it not worked. but when I opened
the python console and writed line by line the same code of the .py file, it worked.

the .py file:
`import serial`
`ser = serial.Serial('com5')`
`ser.write('L'.encode())`
`ser.close()`

it not worked.

on the python console:
**python**>> `import serial`
**python**>> `ser = serial.Serial('com5')`
**python**>> `ser.write('L'.encode())`
**python**>> `ser.close()`

It worked.

**Comment by pradyunsg** [comment]
Hi! Thanks for filing this but this isn't the right place for this issue.

This issue tracker is for the infrastructure for Python that is managed by the Python Software Foundation (such as python.org, bugs.python.org, docs.python.org etc), not for pyserial and for getting help related to it.

I think that the [pyserial issue tracker](https://github.com/pyserial/pyserial/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), [python-list](https://mail.python.org/mailman/listinfo/python-list) mailing list, [#python on Freenode](https://webchat.freenode.net/?channels=%23python) (IRC) or [StackOverflow](https://stackoverflow.com) would be better channels to get help with the issue you're facing.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
