### ISSUE TITLE
psf-infra-meta should point to bpo

### ISSUE THREAD

**Issue by E-Paine** [python/psf-infra-meta#79]
Of the latest 10 issues on this tracker (when I last looked), a significant number were not suited to it. A lot of new contributors are coming here to report standard Python bugs which should be on bpo. I believe the solution is to make it very clear in the README for this project that bpo is *the* place to go for Python bugs (I think it is already clear this is a meta-tracker and so this does not need changing).

Personally, I think we keep the first line description ("Meta-repository...") where it is, but the second line should be something like this (in bold):

**If you are reporting a bug with Python, please do so on [bugs.python.org](bugs.python.org).**

**Comment by pradyunsg** [comment]
It might also make sense to add an issue template telling users "if you're filing a bug related to Python itself, use b.p.o. if you're filing an issue to get help/support, consider opening a question on Stackoverflow" or something along those lines.
