### ISSUE TITLE
element isn't printed if the previous element is deleted from the list using for loop

### ISSUE THREAD

**Issue by ghost** [python/psf-infra-meta#82]
![Code Playground _ SoloLearn_ Learn to code for FREE! - Google Chrome 17-09-2020 17_03_54](https://user-images.githubusercontent.com/59786025/93465077-e5942500-f907-11ea-954c-5aa2515c668f.png)
![Code Playground _ SoloLearn_ Learn to code for FREE! - Google Chrome 17-09-2020 17_03_54](https://user-images.githubusercontent.com/59786025/93465086-e7f67f00-f907-11ea-8bad-b0b9f32f7dc9.png)

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
