### ISSUE TITLE
ipaddress Library gives me incorrect results

### ISSUE THREAD

**Issue by AnudeepBalla** [python/psf-infra-meta#83]
https://docs.python.org/3.8/library/ipaddress.html

```
import ipaddress


ADDRESSES = [
    '172.16.254.00'
]

for ip in ADDRESSES:
    addr = ipaddress.ip_address(ip)
    if addr.version==4:
        {
            print("true")
        }
    else:
        {
            print("false")
        }
```
![Screen Shot 2020-09-20 at 1 33 30 AM](https://user-images.githubusercontent.com/58192427/93705253-4cb90180-fae1-11ea-9268-8f6194faa793.png)

I tried to validate an invalid IPv4 address using IPaddress library from py 3.8.6 but somehow it considers any address ending with "00" to be valid. 

I hope this is helpful to the community please let me know if the issue is with validation from your end or a bug in the library.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
