### ISSUE TITLE
Python string function "strip()" bug

### ISSUE THREAD

**Issue by mailmrcai** [python/psf-infra-meta#85]
In [1]: example_str = "es_e"
In [2]: example_str.strip("es_")
Out[2]: ''

In [3]: example_str = "es_eabc"
In [4]: example_str.strip("es_")
Out[4]: 'abc'
#why the last "e" is stripped ?

**Comment by matrixise** [comment]
@ewdurbin Please, could you close this issue? Thank you,

**Comment by ewdurbin** [comment]
@matrixise aside, I've granted you triage permission on this repository for future use.
